"""empty message

Revision ID: 6261c67e64c4
Revises: 840d9b2e1888
Create Date: 2023-03-22 13:47:51.155926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6261c67e64c4'
down_revision = '840d9b2e1888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelved_book', schema=None) as batch_op:
        batch_op.alter_column('avg_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1, asdecimal=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelved_book', schema=None) as batch_op:
        batch_op.alter_column('avg_rating',
               existing_type=sa.Float(precision=1, asdecimal=1),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
